{
 "title": "Fluss – detail",
 "tags": [ "fluss" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Fluss – CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluss_coordinator_status_JVM_CPU_load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_CPU_load\n\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_CPU_load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_CPU_load",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_CPU_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 465 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_CPU_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_CPU_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 465 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_CPU_time",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluss – memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "coordinator_status_JVM_memory_heap_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_heap_used",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_heap_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_heap_used",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_heap_committed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_heap_committed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_heap_committed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_heap_committed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_heap_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_heap_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_heap_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 274 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_heap_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_nonHeap_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_nonHeap_used",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_nonHeap_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 282 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_nonHeap_used",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_nonHeap_committed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_nonHeap_committed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_nonHeap_committed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 290 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_nonHeap_committed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_nonHeap_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_nonHeap_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_nonHeap_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 298 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_nonHeap_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_metaspace_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_metaspace_used",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_metaspace_used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 306 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_metaspace_used",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_metaspace_committed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_metaspace_committed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_metaspace_committed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 314 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_metaspace_committed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_metaspace_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_metaspace_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_metaspace_max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 322 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_metaspace_max",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_direct_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_direct_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_direct_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 330 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_direct_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_direct_memoryUsed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_direct_memoryUsed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_direct_memoryUsed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 338 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_direct_memoryUsed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_direct_totalCapacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 346 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_direct_totalCapacity",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_direct_totalCapacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 346 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_direct_totalCapacity",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_mapped_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 354 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_mapped_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_mapped_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 354 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_mapped_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_mapped_memoryUsed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 362 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_mapped_memoryUsed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_mapped_memoryUsed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 362 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_mapped_memoryUsed",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_memory_mapped_totalCapacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 370 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_memory_mapped_totalCapacity",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_memory_mapped_totalCapacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 370 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_memory_mapped_totalCapacity",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluss – threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluss_coordinator_status_JVM_threads_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_threads_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_threads_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_threads_count",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluss – garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluss_coordinator_status_JVM_GC_all_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_GC_all_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_status_JVM_GC_all_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fluss_coordinator_status_JVM_GC_all_time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_GC_all_count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_GC_all_count",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_status_JVM_GC_all_time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_status_JVM_GC_all_time",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluss – CoordinatorServer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluss_coordinator_activeCoordinatorCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_activeCoordinatorCount",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_activeTabletServerCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_activeTabletServerCount",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_offlineBucketCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_offlineBucketCount",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_coordinator_tableCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "fluss_coordinator_tableCount", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Fluss – TabletServer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluss_tabletserver_replicationBytesInPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_replicationBytesInPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_replicationBytesInPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_replicationBytesOutPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_leaderCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "fluss_tabletserver_leaderCount", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "fluss_tabletserver_replicaCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 134 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_replicaCount",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_writerIdCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_writerIdCount",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_delayedOperationsSize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_delayedOperationsSize",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluss – request",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluss_coordinator_request_requestQueueSize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_coordinator_request_requestQueueSize",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_request_requestQueueSize",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_request_requestQueueSize",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_request_requestPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_request_requestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_request_errorsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_request_errorsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_request_totalTimeMs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_request_totalTimeMs",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_request_requestProcessTimeMs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_request_requestProcessTimeMs",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_request_requestQueueTimeMs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_request_requestQueueTimeMs",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Fluss – table/bucket",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "fluss_tabletserver_table__messagesInPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "mps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__messagesInPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__bytesInPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__bytesInPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__bytesOutPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__bytesOutPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__totalFetchLogRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__totalFetchLogRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__failedFetchLogRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__failedFetchLogRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__totalPutKvRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__totalPutKvRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__failedPutKvRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__failedPutKvRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__totalLookupRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__totalLookupRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__failedLookupRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__failedLookupRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__remoteLogCopyBytesPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__remoteLogCopyBytesPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__remoteLogCopyRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__remoteLogCopyRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__remoteLogCopyErrorPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__remoteLogCopyErrorPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__remoteLogDeleteRequestsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__remoteLogDeleteRequestsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table__remoteLogDeleteErrorPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table__remoteLogDeleteErrorPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_inSyncReplicasCount",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_inSyncReplicasCount",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_underMinIsr",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_underMinIsr",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_atMinIsr",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_atMinIsr",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_isrExpandsPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_isrExpandsPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_isrShrinksPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_isrShrinksPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_failedIsrUpdatesPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_failedIsrUpdatesPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_log_numSegments",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_log_numSegments",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_log_endOffset",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_log_endOffset",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_log_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_log_size",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_log_flushPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "eps" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_log_flushPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_log_flushLatencyMs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_log_flushLatencyMs",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_remoteLog_numSegments",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_remoteLog_numSegments",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_remoteLog_endOffset",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_remoteLog_endOffset",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "fluss_tabletserver_table_bucket_remoteLog_size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "fluss_tabletserver_table_bucket_remoteLog_size",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Flink – connector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "flink_taskmanager_job_task_operator_currentEmitEventTimeLag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 657 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_currentEmitEventTimeLag",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_taskmanager_job_task_operator_currentFetchEventTimeLag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 657 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_currentFetchEventTimeLag",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_taskmanager_job_task_operator_numBytesOut",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 665 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numBytesOut",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_taskmanager_job_task_operator_numBytesOutPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 665 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numBytesOutPerSecond",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_taskmanager_job_task_operator_numRecordsOut",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 673 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsOut",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 673 },
     "fieldConfig": { "defaults": { "unit": "recps" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Flink – CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "flink_jobmanager_Status_JVM_CPU_Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Load\n\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_taskmanager_Status_JVM_CPU_Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load\n\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_jobmanager_Status_JVM_CPU_Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_CPU_Time",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "flink_taskmanager_Status_JVM_CPU_Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Time",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}