{
 "title": "Fluss – overview",
 "tags": [ "fluss" ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CoordinatorServer – # active instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluss_coordinator_activeCoordinatorCount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TabletServer – # active instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluss_coordinator_activeTabletServerCount",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# tables",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fluss_coordinator_tableCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "# buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fluss_coordinator_bucketCount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CoordinatorServer instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluss_coordinator_status_JVM_CPU_load*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TabletServer instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluss_tabletserver_status_JVM_CPU_load*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TabletServer instances – min. CPU load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(fluss_tabletserver_status_JVM_CPU_load)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TabletServer instances – max. CPU load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(fluss_tabletserver_status_JVM_CPU_load)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink JobManager",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_CPU_Load*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink TaskManager – # active instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink TaskManager – # available slots",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsAvailable",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Flink jobs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRunningJobs",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink TaskManager instances",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 14, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "flink_taskmanager_Status_JVM_CPU_Load*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink TaskManager instances – min. CPU load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(flink_taskmanager_Status_JVM_CPU_Load)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink TaskManager instances – max. CPU load",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 13, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(flink_taskmanager_Status_JVM_CPU_Load)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TabletServer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "TabletServer – in total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_id) (fluss_tabletserver_table__messagesInPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TabletServer – in total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_id) (fluss_tabletserver_table__bytesInPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TabletServer – out total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(cluster_id) (fluss_tabletserver_table__bytesOutPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Flink connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Flink – out",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "recps" } },
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_numRecordsOutPerSecond",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}