# .github/workflows/ci-template.yaml
name: CI Template

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      maven-parameters:
        description: "Any parameters of the Maven command."
        required: false
        type: string
        default: ""
jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin'
      - name: Build
        run: |
          mvn -T 1C -B clean install -DskipTests ${{ steps.profile.outputs.maven_profile }}
      - name: Test
        timeout-minutes: 60
        run: |
          TEST_MODULES=$(./.github/workflows/stage.sh ${{ matrix.module }})
          echo "github ref: ${{ github.ref }}"
          echo "Start testing modules: $TEST_MODULES"
          mvn -B verify $TEST_MODULES -Ptest-coverage -Ptest-${{ matrix.module }} -Dlog.dir=${{ runner.temp }}/fluss-logs -Dlog4j.configurationFile=${{ github.workspace }}/tools/ci/log4j.properties ${{ inputs.maven-parameters }}
        env:
          MAVEN_OPTS: -Xmx4096m
          ARTIFACTS_OSS_ENDPOINT: ${{ secrets.ARTIFACTS_OSS_ENDPOINT }}
          ARTIFACTS_OSS_REGION: ${{ secrets.ARTIFACTS_OSS_REGION }}
          ARTIFACTS_OSS_BUCKET: ${{ secrets.ARTIFACTS_OSS_BUCKET }}
          ARTIFACTS_OSS_ACCESS_KEY: ${{ secrets.ARTIFACTS_OSS_ACCESS_KEY }}
          ARTIFACTS_OSS_SECRET_KEY: ${{ secrets.ARTIFACTS_OSS_SECRET_KEY }}
          ARTIFACTS_OSS_STS_ENDPOINT: ${{ secrets.ARTIFACTS_OSS_STS_ENDPOINT }}
          ARTIFACTS_OSS_ROLE_ARN: ${{ secrets.ARTIFACTS_OSS_ROLE_ARN }}
      - name: Upload build logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: logs-test-${{ matrix.module }}-${{ github.run_number}}#${{ github.run_attempt }}
          path: ${{ runner.temp }}/fluss-logs/*
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        with:
          name: jacoco-report-${{ matrix.module }}-${{ github.run_number}}#${{ github.run_attempt }}
          path: ${{ github.workspace }}/fluss-test-coverage/target/site/jacoco-aggregate/*